FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY pom.xml .
COPY src ./src

COPY .mvn .mvn
COPY mvnw .
RUN ./mvnw clean package -DskipTests

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "target/analytics-0.0.1-SNAPSHOT.jar"]
